name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: '20.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm test -- --coverage
      - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 #v4.5.0
        with:
          file: coverage/lcov.info
          disable_search: true
          use_oidc: true
      - run: npm run build
      - run: npm run docs
