name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: '20.x'
      - run: yarn --immutable
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test --coverage
      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d #v3.1.4
        with:
          file: coverage/lcov.info
      - run: yarn build
      - run: yarn docs
