name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: '20.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm test -- --coverage
      - uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed #v4.3.0
        with:
          file: coverage/lcov.info
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: npm run build
      - run: npm run docs
