name: release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version number (x.y.z)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn --immutable
      - name: npm version
        working-directory: src
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          npm version ${{ inputs.version }}
          git commit -m v${{ inputs.version }}
          git tag v${{ inputs.version }}
      - run: git show HEAD
      - run: yarn build
      - run: yarn docs
      - name: npm login
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami
      - run: npm publish --access=public
        working-directory: dist/package
      - name: npm logout
        run: rm ~/.npmrc
      - run: git push origin master v${{ inputs.version }}
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: Publish documentation
        working-directory: gh-pages
        run: |
          rm -rf *
          cp -a ../dist/docs/* .
          git add .
          git commit --allow-empty -a -m "Updating from ${{ github.sha }}"
          git push origin gh-pages
