name: update

on:
  schedule:
    - cron: '0 3 2 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
      - run: npm ci
      - run: npx npm-check-updates -u --peer
      - run: npm install --ignore-scripts
      - run: npm update --ignore-scripts
      - name: Create pull request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          commit-message: 'chore: Update all dependencies'
          branch: dependencies
          title: Update all dependencies
          body: Update all dependencies
