name: update

on:
  schedule:
    - cron: '0 3 2 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn set version stable
      - run: yarn install --no-immutable
      - run: yarn up --caret '**'
      - run: yarn up -R '**'
      - name: Create pull request
        uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7 # v4.2.0
        with:
          commit-message: 'chore: Update all dependencies'
          branch: dependencies
          title: Update all dependencies
          body: Update all dependencies
